import type { Property, Broker, Amenity } from './types';
import { Wifi, ParkingSquare, PawPrint, VenetianMask, Utensils, Droplets, Snowflake, Dumbbell, Sun } from 'lucide-react';

export const amenities: Amenity[] = [
  { name: 'WiFi', icon: Wifi },
  { name: 'Parking', icon: ParkingSquare },
  { name: 'Pet Friendly', icon: PawPrint },
  { name: 'Balcony', icon: VenetianMask },
  { name: 'Kitchen', icon: Utensils },
  { name: 'Pool', icon: Droplets },
  { name: 'Air Conditioning', icon: Snowflake },
  { name: 'Gym', icon: Dumbbell },
  { name: 'Rooftop Deck', icon: Sun },
];

export const brokers: Broker[] = [
  {
    id: 'broker-1',
    name: 'Jane Doe',
    email: 'jane.doe@apexestates.com',
    phone: '(555) 123-4567',
    avatarId: 'broker-1-avatar',
  },
  {
    id: 'broker-2',
    name: 'John Smith',
    email: 'john.smith@apexestates.com',
    phone: '(555) 987-6543',
    avatarId: 'broker-2-avatar',
  },
];

export const properties: Property[] = [
  {
    id: 'prop-1',
    title: 'Modern Villa with Ocean View',
    description: 'A stunning modern villa offering breathtaking ocean views. Features an open-plan living space, infinity pool, and state-of-the-art kitchen. Perfect for those seeking luxury and tranquility.',
    type: 'sale',
    price: 4500000,
    location: 'Malibu, CA',
    address: '25800 Pacific Coast Hwy, Malibu, CA 90265',
    coordinates: { lat: 34.038, lng: -118.689 },
    bedrooms: 5,
    bathrooms: 6,
    area: 5200,
    imageIds: ['property-1-ext', 'property-1-int-1', 'property-1-int-2'],
    amenities: ['WiFi', 'Parking', 'Pool', 'Air Conditioning', 'Kitchen'],
    floorPlanId: 'property-1-plan',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    brokerId: 'broker-1',
    status: 'available',
    vrTourUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0&autoplay=1&mute=1&loop=1&playlist=dQw4w9WgXcQ",
    nearbyPlaces: [
        { name: 'UCLA Medical Center', type: 'hospital', distance: '1.2 miles' },
        { name: 'Malibu High School', type: 'school', distance: '0.8 miles' },
        { name: 'Nobu Malibu', type: 'restaurant', distance: '0.5 miles' },
    ]
  },
  {
    id: 'prop-2',
    title: 'Chic Downtown Loft',
    description: 'A stylish and spacious loft apartment in the heart of the city. High ceilings, large windows, and an industrial-chic design create a unique urban living experience. Steps away from top restaurants and nightlife.',
    type: 'rent',
    price: 7500,
    location: 'New York, NY',
    address: '158 Mercer St, New York, NY 10012',
    coordinates: { lat: 40.725, lng: -74.000 },
    bedrooms: 2,
    bathrooms: 2,
    area: 1800,
    imageIds: ['property-2-ext', 'property-2-int-1', 'property-2-int-2'],
    amenities: ['WiFi', 'Air Conditioning', 'Pet Friendly', 'Gym'],
    floorPlanId: 'property-2-plan',
    brokerId: 'broker-2',
    status: 'available',
  },
  {
    id: 'prop-3',
    title: 'Cozy Suburban Family Home',
    description: 'Charming family home in a quiet, friendly suburb. Features a large backyard with a deck, a newly renovated kitchen, and a cozy fireplace. Excellent school district and close to parks.',
    type: 'sale',
    price: 850000,
    location: 'Austin, TX',
    address: '4501 Speedway, Austin, TX 78751',
    coordinates: { lat: 30.307, lng: -97.720 },
    bedrooms: 4,
    bathrooms: 3,
    area: 2600,
    imageIds: ['property-3-ext', 'property-3-int-1'],
    amenities: ['Parking', 'Pet Friendly', 'Kitchen', 'Air Conditioning', 'WiFi'],
    floorPlanId: 'property-3-plan',
    brokerId: 'broker-1',
    status: 'available',
  },
  {
    id: 'prop-4',
    title: 'Luxury Penthouse with Rooftop Deck',
    description: 'Experience the height of luxury in this stunning penthouse. Unobstructed 360-degree city views, a private rooftop deck with a jacuzzi, and premium designer finishes throughout.',
    type: 'sale',
    price: 12500000,
    location: 'Miami, FL',
    address: '1000 S Pointe Dr, Miami Beach, FL 33139',
    coordinates: { lat: 25.765, lng: -80.136 },
    bedrooms: 4,
    bathrooms: 5,
    area: 4500,
    imageIds: ['property-4-ext', 'property-4-int-1'],
    amenities: ['Pool', 'Gym', 'Rooftop Deck', 'Parking', 'Air Conditioning', 'WiFi'],
    floorPlanId: 'property-4-plan',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    brokerId: 'broker-2',
    status: 'sold',
  },
  {
    id: 'prop-5',
    title: 'Modern Townhouse',
    description: 'Sleek and modern townhouse in a vibrant, walkable neighborhood. Close to shops, cafes, and public transport. Features a private patio and energy-efficient appliances.',
    type: 'rent',
    price: 4200,
    location: 'San Francisco, CA',
    address: '300 Page St, San Francisco, CA 94102',
    coordinates: { lat: 37.773, lng: -122.425 },
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    imageIds: ['property-5-ext', 'property-5-int-1'],
    amenities: ['WiFi', 'Kitchen', 'Balcony', 'Parking'],
    floorPlanId: 'property-5-plan',
    brokerId: 'broker-1',
    status: 'available',
  },
  {
    id: 'prop-6',
    title: 'Stunning Beachfront Property',
    description: 'An incredible beachfront property with direct access to the sand. Wake up to the sound of waves and enjoy stunning sunsets from your private balcony. A true paradise.',
    type: 'sale',
    price: 6200000,
    location: 'San Diego, CA',
    address: '3790 Ocean Front Walk, San Diego, CA 92109',
    coordinates: { lat: 32.802, lng: -117.256 },
    bedrooms: 4,
    bathrooms: 4,
    area: 3100,
    imageIds: ['property-6-ext', 'property-6-int-1'],
    amenities: ['Balcony', 'Parking', 'Kitchen', 'WiFi'],
    floorPlanId: 'property-6-plan',
    brokerId: 'broker-2',
    status: 'rented',
  },
];
