import type { Property, Broker, Amenity } from './types';
import { Wifi, ParkingSquare, PawPrint, VenetianMask, Utensils, Droplets, Snowflake, Dumbbell, Sun } from 'lucide-react';
import { sub } from 'date-fns';

export const amenities: Amenity[] = [
  { name: 'WiFi', icon: Wifi },
  { name: 'Parking', icon: ParkingSquare },
  { name: 'Pet Friendly', icon: PawPrint },
  { name: 'Balcony', icon: VenetianMask },
  { name: 'Kitchen', icon: Utensils },
  { name: 'Pool', icon: Droplets },
  { name: 'Generator Backup', icon: Snowflake }, // Adapted for local context
  { name: 'Gym', icon: Dumbbell },
  { name: 'Rooftop Deck', icon: Sun },
];

export const brokers: Broker[] = [
  {
    id: 'broker-1',
    name: 'Abebe Kebede',
    email: 'abebe.k@addisestates.et',
    phone: '+251 911 123 456',
    avatarId: 'broker-1-avatar',
  },
  {
    id: 'broker-2',
    name: 'Selamawit Tesfaye',
    email: 'selam.t@addisestates.et',
    phone: '+251 922 987 654',
    avatarId: 'broker-2-avatar',
  },
];

export const properties: Property[] = [
  {
    id: 'prop-1',
    title: 'Luxury Villa in Old Airport',
    description: 'A stunning modern villa located in the prestigious Old Airport area. Features high ceilings, a lush garden, and premium finishes. Ideal for diplomats and executives seeking security and elegance.',
    type: 'sale',
    category: 'villa',
    price: 125000000,
    location: 'Old Airport, Addis Ababa',
    address: 'Near ICS, Old Airport, Addis Ababa',
    coordinates: { lat: 8.995, lng: 38.730 },
    bedrooms: 5,
    bathrooms: 6,
    area: 600,
    imageIds: ['property-1-ext', 'property-1-int-1', 'property-1-int-2', 'property-1-int-3', 'property-1-bath'],
    amenities: ['WiFi', 'Parking', 'Pool', 'Generator Backup', 'Kitchen'],
    floorPlanId: 'property-1-plan',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    brokerId: 'broker-1',
    status: 'available',
    vrTourUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0&autoplay=1&mute=1&loop=1&playlist=dQw4w9WgXcQ",
    nearbyPlaces: [
        { name: 'International Community School (ICS)', type: 'school', distance: '0.4 km' },
        { name: 'African Union Headquarters', type: 'hospital', distance: '2.5 km' },
        { name: 'Vibe Club', type: 'restaurant', distance: '0.8 km' },
        { name: 'Laphto Mall', type: 'mall', distance: '1.2 km' },
    ],
    postedOn: sub(new Date(), { days: 10 }).toISOString(),
    views: 1254,
    saves: 231,
    priceHistory: [
      { date: sub(new Date(), { months: 6 }).toISOString(), price: 115000000 },
      { date: sub(new Date(), { months: 1 }).toISOString(), price: 125000000 },
    ],
    environmentalInfo: {
      walkScore: 70,
      bikeScore: 40,
      roadSafety: 80,
      floodRisk: 5,
      noiseLevel: 25,
    }
  },
  {
    id: 'prop-2',
    title: 'Modern Apartment in Bole',
    description: 'A stylish and spacious apartment in the heart of Bole Atlas. Steps away from the city\'s best cafes, restaurants, and nightlife. Includes 24/7 security and a backup generator.',
    type: 'rent',
    category: 'apartment',
    price: 150000,
    location: 'Bole, Addis Ababa',
    address: 'Bole Atlas, Near Edna Mall, Addis Ababa',
    coordinates: { lat: 8.998, lng: 38.785 },
    bedrooms: 3,
    bathrooms: 3,
    area: 220,
    imageIds: ['property-2-ext', 'property-2-int-1', 'property-2-int-2', 'property-2-int-3'],
    amenities: ['WiFi', 'Generator Backup', 'Pet Friendly', 'Gym'],
    floorPlanId: 'property-2-plan',
    brokerId: 'broker-2',
    status: 'available',
    nearbyPlaces: [
        { name: 'Hayat Hospital', type: 'hospital', distance: '1.0 km' },
        { name: 'Edna Mall', type: 'mall', distance: '0.5 km' },
        { name: 'Bole Medhanialem Church', type: 'transport', distance: '0.6 km' },
        { name: 'Kuriftu Entoto', type: 'gym', distance: '4.5 km' },
    ],
    postedOn: sub(new Date(), { days: 5 }).toISOString(),
    views: 890,
    saves: 150,
    priceHistory: [],
    environmentalInfo: {
        walkScore: 95,
        bikeScore: 50,
        roadSafety: 65,
        floodRisk: 10,
        noiseLevel: 70,
    }
  },
  {
    id: 'prop-3',
    title: 'Cozy Family Home in CMC',
    description: 'Charming family home in the quiet residential area of CMC. Features a beautiful garden, modern kitchen, and safe surroundings. Close to the Light Rail station.',
    type: 'sale',
    category: 'house',
    price: 45000000,
    location: 'CMC, Addis Ababa',
    address: 'CMC Residential Area, Near St. Michael Church, Addis Ababa',
    coordinates: { lat: 9.010, lng: 38.840 },
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
    imageIds: ['property-3-ext', 'property-3-int-1', 'property-3-int-2'],
    amenities: ['Parking', 'Pet Friendly', 'Kitchen', 'Generator Backup', 'WiFi'],
    floorPlanId: 'property-3-plan',
    brokerId: 'broker-1',
    status: 'available',
    nearbyPlaces: [
        { name: 'School of Tomorrow', type: 'school', distance: '0.8 km' },
        { name: 'Shoa Supermarket', type: 'mall', distance: '1.2 km' },
        { name: 'CMC Light Rail Station', type: 'playground', distance: '0.5 km' },
    ],
    postedOn: sub(new Date(), { days: 32 }).toISOString(),
    views: 2300,
    saves: 410,
    priceHistory: [
        { date: sub(new Date(), { months: 4 }).toISOString(), price: 42000000 },
        { date: sub(new Date(), { months: 2 }).toISOString(), price: 45000000 },
    ],
    environmentalInfo: {
        walkScore: 65,
        bikeScore: 30,
        roadSafety: 85,
        floodRisk: 15,
        noiseLevel: 35,
    }
  },
  {
    id: 'prop-4',
    title: 'Executive Penthouse in Kazanchis',
    description: 'High-end penthouse overlooking the city skyline. Proximity to the UN-ECA and major hotels makes this the perfect spot for international consultants and diplomats.',
    type: 'sale',
    category: 'condominium',
    price: 85000000,
    location: 'Kazanchis, Addis Ababa',
    address: 'Kirkos Subcity, Kazanchis, Addis Ababa',
    coordinates: { lat: 9.020, lng: 38.765 },
    bedrooms: 4,
    bathrooms: 4,
    area: 400,
    imageIds: ['property-4-ext', 'property-4-int-1', 'property-4-int-2'],
    amenities: ['Pool', 'Gym', 'Rooftop Deck', 'Parking', 'Generator Backup', 'WiFi'],
    floorPlanId: 'property-4-plan',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    brokerId: 'broker-2',
    status: 'sold',
    nearbyPlaces: [
        { name: 'UN-ECA', type: 'school', distance: '0.3 km' },
        { name: 'Sheraton Addis', type: 'restaurant', distance: '1.0 km' },
        { name: 'Unity Park', type: 'playground', distance: '1.5 km' },
    ],
    postedOn: sub(new Date(), { days: 90 }).toISOString(),
    views: 15000,
    saves: 1200,
    priceHistory: [
      { date: sub(new Date(), { months: 3 }).toISOString(), price: 85000000 },
    ],
    environmentalInfo: {
        walkScore: 90,
        bikeScore: 20,
        roadSafety: 70,
        floodRisk: 5,
        noiseLevel: 65,
    }
  }
];